# Build the application from source
FROM golang:1.20 AS build-stage

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 GOOS=linux go build -pkgdir pkg -o /ilt-6 ./cmd/ilt-6/main.go

# Deploy the application binary into a lean image
FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY --from=build-stage /ilt-6 /ilt-6
COPY assets ./assets

EXPOSE 80

USER nonroot:nonroot

ENTRYPOINT ["/ilt-6"]
