# Build the application from source
FROM golang:1.19 AS build-stage

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 GOOS=linux go build -pkgdir pkg -o /ilt-4 ./cmd/ilt-4/main.go

# Deploy the application binary into a lean image
FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY --from=build-stage /ilt-4 /ilt-4

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/ilt-4"]
